version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v21.03.2
    volumes:
      - ./data:/dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - dgraph

  alpha:
    image: dgraph/dgraph:v21.03.2
    environment: 
      DGRAPH_ALPHA_GRAPHQL_LAMBDA_URL: "http://lambda:8686/graphql-worker"
    volumes:
      - ./data:/dgraph
    ports:
      - 8080:8080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --graphql lambda-url=http://lambda:8686/graphql-worker --security "whitelist=0.0.0.0/0"
    networks:
      - dgraph

  lambda:
    build: .
    environment:
      DGRAPH_URL: alpha
    volumes:
      - .:/lambda
    networks:
      - dgraph

networks:
  dgraph:
    driver: bridge
    name: dgraph
